### ISSUE TITLE
BLE connection times out immediately when using ULP to wake up

### ISSUE THREAD

**Issue by AlexHartford** [h2zero/esp-nimble-cpp#46]
Hi there, we are very new to ESP32 and IOT in general. We have successfully used this library to connect to various devices via bluetooth, and are able to send/receive data. However, after [adding some assembly code](https://github.com/platformio/platform-espressif32/tree/develop/examples/espidf-ulp-pulse/ulp) to achieve a ULP mode, attempting to connect to the device using bluetooth yields an immediate disconnect or timeout.

We are hoping you may have any insight as to why this addition could be breaking our BLE functionality. [This is a minimal example with most of our functionality stripped out](https://github.com/AlexHartford/esp32-ble-test).

**Comment by h2zero** [comment]
Hi @AlexHartford, it is my understanding that using the radio is not possible with the ULP.

**Comment by AlexHartford** [comment]
@h2zero We're not actually trying to use the bluetooth _while in ULP_, but rather after waking up. In the example, ULP is there for a power button and while the device is powered on (not in ULP mode) is when we are facing the bluetooth issues. 

Thanks for the quick reply!

**Comment by h2zero** [comment]
Ahh ok, I didn't see any deinit of the ble stack in the code so I assumed that is what you were doing, sorry.

What you'll need to do is call `NimBLEdevice::deinit(true);` before entering low power mode and then reinitialize after wake up.

That should solve the issue.

**Comment by AlexHartford** [comment]
We added in deinit prior to sleep. It didn't fix the issue unfortunately. To clarify, it won't connect at any time, not only after entering deep sleep. We attached the serial monitor and phone connection logs in case that helps figure this out. (serial monitor is first, phone is second).

Serial monitor:
```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4
load:0x3fff0034,len:7284
load:0x40078000,len:13212
load:0x40080400,len:4568
entry 0x400806f4
␛[0;32mI (29) boot: ESP-IDF 3.40200.210118 2nd stage bootloader␛[0m
␛[0;32mI (29) boot: compile time 20:31:30␛[0m
␛[0;32mI (29) boot: chip revision: 3␛[0m
␛[0;32mI (33) boot_comm: chip revision: 3, min. bootloader chip revision: 0␛[0m
␛[0;32mI (40) boot.esp32: SPI Speed      : 80MHz␛[0m
␛[0;32mI (45) boot.esp32: SPI Mode       : DIO␛[0m
␛[0;32mI (49) boot.esp32: SPI Flash Size : 16MB␛[0m
␛[0;32mI (54) boot: Enabling RNG early entropy source...␛[0m
␛[0;32mI (59) boot: Partition Table:␛[0m
␛[0;32mI (63) boot: ## Label            Usage          Type ST Offset   Length␛[0m
␛[0;32mI (70) boot:  0 nvs              WiFi data        01 02 00009000 00005000␛[0m
␛[0;32mI (77) boot:  1 otadata          OTA data         01 00 0000e000 00002000␛[0m
␛[0;32mI (85) boot:  2 app0             OTA app          00 10 00010000 00730000␛[0m
␛[0;32mI (92) boot:  3 app1             OTA app          00 11 00740000 00730000␛[0m
␛[0;32mI (100) boot:  4 spiffs           Unknown data     01 82 00e70000 00006000␛[0m
␛[0;32mI (107) boot:  5 fctry            WiFi data        01 02 00e76000 00004000␛[0m
␛[0;32mI (115) boot: End of partition table␛[0m
␛[0;32mI (119) boot: No factory image, trying OTA 0␛[0m
␛[0;32mI (124) boot_comm: chip revision: 3, min. application chip revision: 0␛[0m
␛[0;32mI (131) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x11d54 ( 73044) map␛[0m
␛[0;32mI (164) esp_image: segment 1: paddr=0x00021d7c vaddr=0x3ffbdb60 size=0x03440 ( 13376) load␛[0m
␛[0;32mI (169) esp_image: segment 2: paddr=0x000251c4 vaddr=0x40080000 size=0x00404 (  1028) load␛[0m
␛[0;32mI (171) esp_image: segment 3: paddr=0x000255d0 vaddr=0x40080404 size=0x0aa48 ( 43592) load␛[0m
␛[0;32mI (196) esp_image: segment 4: paddr=0x00030020 vaddr=0x400d0020 size=0x5ea00 (387584) map␛[0m
␛[0;32mI (321) esp_image: segment 5: paddr=0x0008ea28 vaddr=0x4008ae4c size=0x0b264 ( 45668) load␛[0m
␛[0;32mI (338) esp_image: segment 6: paddr=0x00099c94 vaddr=0x400c0000 size=0x00064 (   100) load␛[0m
␛[0;32mI (351) boot: Loaded app from partition at offset 0x10000␛[0m
␛[0;32mI (364) boot: Set actual ota_seq=1 in otadata[0]␛[0m
␛[0;32mI (365) boot: Disabling RNG early entropy source...␛[0m
␛[0;32mI (365) cpu_start: Pro cpu up.␛[0m
␛[0;32mI (368) cpu_start: Application information:␛[0m
␛[0;32mI (373) cpu_start: Project name:     esp32-ble-test␛[0m
␛[0;32mI (378) cpu_start: App version:      2a53651␛[0m
␛[0;32mI (383) cpu_start: Compile time:     Jun  1 2021 20:30:46␛[0m
␛[0;32mI (389) cpu_start: ELF file SHA256:  904d254efe1d21d5...␛[0m
␛[0;32mI (395) cpu_start: ESP-IDF:          3.40200.210118␛[0m
␛[0;32mI (401) cpu_start: Starting app cpu, entry point is 0x40081324␛[0m
␛[0;32mI (0) cpu_start: App cpu up.␛[0m
␛[0;32mI (411) heap_init: Initializing. RAM available for dynamic allocation:␛[0m
␛[0;32mI (418) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM␛[0m
␛[0;32mI (424) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM␛[0m
␛[0;32mI (430) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM␛[0m
␛[0;32mI (436) heap_init: At 3FFC3C00 len 0001C400 (113 KiB): DRAM␛[0m
␛[0;32mI (443) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM␛[0m
␛[0;32mI (449) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM␛[0m
␛[0;32mI (455) heap_init: At 400960B0 len 00009F50 (39 KiB): IRAM␛[0m
␛[0;32mI (462) cpu_start: Pro cpu start user code␛[0m
␛[0;32mI (479) spi_flash: detected chip: gd␛[0m
␛[0;32mI (480) spi_flash: flash io: dio␛[0m
␛[0;32mI (480) cpu_start: Starting scheduler on PRO CPU.␛[0m
␛[0;32mI (0) cpu_start: Starting scheduler on APP CPU.␛[0m
Starting main
Not ULP wakeup, initializing main prog
Starting NimBLE Server
␛[0;32mI (3544) BTDM_INIT: BT controller compile version [a4c513b]␛[0m
␛[0;32mI (3544) system_api: Base MAC address is not set␛[0m
␛[0;32mI (3544) system_api: read default base MAC address from EFUSE␛[0m
␛[0;32mI (3554) phy_init: phy_version 4660,0162888,Dec 23 2020␛[0m
␛[0;32mI (3894) NimBLEDevice: BLE Host Task Started␛[0m
␛[0;32mI (3924) NimBLEDevice: NimBle host synced.␛[0m
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
Advertising Started
␛[0;32mI (3934) gpio: GPIO[13]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
␛[0;32mI (3944) gpio: GPIO[14]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
␛[0;32mI (3954) gpio: GPIO[19]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
␛[0;32mI (3964) gpio: GPIO[21]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
Button thread created...
Before main loop...
Client connected
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
Client address: 61:16:5e:47:7c:4a
GAP procedure initiated: connection parameter update; conn_handle=0 itvl_min=24 itvl_max=48 latency=0 supervision_timeout=120 min_ce_len=0 max_ce_len=0
Client disconnected - start advertising
␛[0;33mW (28434) NimBLEAdvertising: Advertising already active␛[0m
␛[0;33mW (28434) NimBLEAdvertising: Advertising already active␛[0m
```

Phone:
```
Connecting to 10:52:1C:88:6C::AE...
[Server] Device with address 10:52:1C:88:6C::AE connected
Connected to 10:52:1C:88:6C::AE
Connection parameters updated (interval: 60.0ms, latency: 0, timeout: 1200ms)
Discovering Services...
Connection parameters updated (interval: 7.5ms, latency: 0, timeout: 5000ms)
Error 8 (0x8) GATT CONN TIMEOUT
Disconnected
[Server] Device disconnected
```

**Comment by h2zero** [comment]
Looks like an issue with conflicting connection parameters.

Try removing `pServer->updateConnParams(desc->conn_handle, 24, 48, 0, 120);` from the onconnect handler.

**Comment by AlexHartford** [comment]
After removing that line, here are the logs from the phone:
```
Connecting to 10:52:1C:88:6C::AE...
[Server] Device with address 10:52:1C:88:6C::AE connected
Connected to 10:52:1C:88:6C::AE
Connection parameters updated (interval: 7.5ms, latency: 0, timeout: 5000ms)
Discovering Services...
[Server] Device disconnected
Error 8 (0x8) GATT CONN TIMEOUT
Disconnected
```

**Comment by h2zero** [comment]
I can't think of anything else that would cause this. 

Could you turn up the log verbosity in menuconfig to debug and share the output when it disconnects?

**Comment by AlexHartford** [comment]
<details>
<summary>Device logs - Click to expand</summary>

```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4
load:0x3fff0034,len:9388
load:0x40078000,len:14056
load:0x40080400,len:4956
entry 0x40080730
␛[0;32mI (29) boot: ESP-IDF 3.40200.210118 2nd stage bootloader␛[0m
␛[0;32mI (29) boot: compile time 16:59:05␛[0m
D (29) bootloader_flash: mmu set block paddr=0x00000000 (was 0xffffffff)␛[0m
␛[0;32mI (36) boot: chip revision: 3␛[0m
␛[0;32mI (40) boot_comm: chip revision: 3, min. bootloader chip revision: 0␛[0m
D (47) boot.esp32: magic e9␛[0m
D (49) boot.esp32: segments 04␛[0m
D (53) boot.esp32: spi_mode 02␛[0m
D (56) boot.esp32: spi_speed 0f␛[0m
D (59) boot.esp32: spi_size 04␛[0m
␛[0;32mI (62) boot.esp32: SPI Speed      : 80MHz␛[0m
␛[0;32mI (67) boot.esp32: SPI Mode       : DIO␛[0m  
␛[0;32mI (71) boot.esp32: SPI Flash Size : 16MB␛[0m
D (76) boot: Enabling RTCWDT(9000 ms)␛[0m
␛[0;32mI (80) boot: Enabling RNG early entropy source...␛[0m
D (85) bootloader_flash: mmu set paddr=00000000 count=1 size=c00 src_addr=8000 src_addr_aligned=0␛[0m
D (94) boot: mapped partition table 0x8000 at 0x3f408000␛[0m
D (99) flash_parts: partition table verified, 7 entries␛[0m
␛[0;32mI (105) boot: Partition Table:␛[0m
␛[0;32mI (108) boot: ## Label            Usage          Type ST Offset   Length␛[0m
D (116) boot: load partition table entry 0x3f408000␛[0m
D (121) boot: type=1 subtype=2␛[0m
␛[0;32mI (124) boot:  0 nvs              WiFi data        01 02 00009000 00005000␛[0m
D (131) boot: load partition table entry 0x3f408020␛[0m
D (136) boot: type=1 subtype=0␛[0m
␛[0;32mI (139) boot:  1 otadata          OTA data         01 00 0000e000 00002000␛[0m
D (147) boot: load partition table entry 0x3f408040␛[0m
D (152) boot: type=0 subtype=10␛[0m
␛[0;32mI (155) boot:  2 app0             OTA app          00 10 00010000 00730000␛[0m
D (163) boot: load partition table entry 0x3f408060␛[0m
D (168) boot: type=0 subtype=11␛[0m
␛[0;32mI (171) boot:  3 app1             OTA app          00 11 00740000 00730000␛[0m
D (178) boot: load partition table entry 0x3f408080␛[0m
D (183) boot: type=1 subtype=82␛[0m
␛[0;32mI (187) boot:  4 spiffs           Unknown data     01 82 00e70000 00006000␛[0m
D (194) boot: load partition table entry 0x3f4080a0␛[0m
D (199) boot: type=1 subtype=2␛[0m
␛[0;32mI (202) boot:  5 fctry            WiFi data        01 02 00e76000 00004000␛[0m
␛[0;32mI (210) boot: End of partition table␛[0m
D (214) boot: OTA data offset 0xe000␛[0m
D (218) bootloader_flash: mmu set paddr=00000000 count=1 size=2000 src_addr=e000 src_addr_aligned=0␛[0m    
D (227) boot: otadata[0]: sequence values 0xffffffff␛[0m
D (232) boot: otadata[1]: sequence values 0xffffffff␛[0m
D (237) boot: OTA sequence numbers both empty (all-0xFF) or partition table does not have bootable ota_apps (app_count=2)␛[0m
␛[0;32mI (248) boot: No factory image, trying OTA 0␛[0m
D (253) boot: Trying partition index 0 offs 0x10000 size 0x730000␛[0m
D (259) esp_image: reading image header @ 0x10000␛[0m
D (264) bootloader_flash: mmu set block paddr=0x00010000 (was 0xffffffff)␛[0m
D (271) esp_image: image header: 0xe9 0x07 0x00 0x04 40081388␛[0m
␛[0;32mI (276) boot_comm: chip revision: 3, min. application chip revision: 0␛[0m
␛[0;32mI (284) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x17984 ( 96644) map␛[0m
D (292) esp_image: free data page_count 0x00000032␛[0m
D (297) bootloader_flash: mmu set paddr=00010000 count=2 size=17984 src_addr=10020 src_addr_aligned=10000␛[0m
D (338) bootloader_flash: mmu set block paddr=0x00020000 (was 0xffffffff)␛[0m
␛[0;32mI (338) esp_image: segment 1: paddr=0x000279ac vaddr=0x3ffbdb60 size=0x034a0 ( 13472) load␛[0m
D (343) esp_image: free data page_count 0x00000032␛[0m
D (348) bootloader_flash: mmu set paddr=00020000 count=1 size=34a0 src_addr=279ac src_addr_aligned=20000␛[0m
D (362) bootloader_flash: mmu set block paddr=0x00020000 (was 0xffffffff)␛[0m
␛[0;32mI (364) esp_image: segment 2: paddr=0x0002ae54 vaddr=0x40080000 size=0x00404 (  1028) load␛[0m
D (373) esp_image: free data page_count 0x00000032␛[0m
D (378) bootloader_flash: mmu set paddr=00020000 count=1 size=404 src_addr=2ae54 src_addr_aligned=20000␛[0mD (388) bootloader_flash: mmu set block paddr=0x00020000 (was 0xffffffff)␛[0m
␛[0;32mI (394) esp_image: segment 3: paddr=0x0002b260 vaddr=0x40080404 size=0x04db8 ( 19896) load␛[0m
D (403) esp_image: free data page_count 0x00000032␛[0m
D (408) bootloader_flash: mmu set paddr=00020000 count=2 size=4db8 src_addr=2b260 src_addr_aligned=20000␛[0m
D (425) bootloader_flash: mmu set block paddr=0x00030000 (was 0xffffffff)␛[0m
␛[0;32mI (425) esp_image: segment 4: paddr=0x00030020 vaddr=0x400d0020 size=0x624d0 (402640) map␛[0m
D (433) esp_image: free data page_count 0x00000032␛[0m
D (438) bootloader_flash: mmu set paddr=00030000 count=7 size=624d0 src_addr=30020 src_addr_aligned=30000[ 
0m
D (577) bootloader_flash: mmu set block paddr=0x00090000 (was 0xffffffff)␛[0m
␛[0;32mI (577) esp_image: segment 5: paddr=0x000924f8 vaddr=0x400851bc size=0x10f60 ( 69472) load␛[0m      
D (581) esp_image: free data page_count 0x00000032␛[0m
D (586) bootloader_flash: mmu set paddr=00090000 count=2 size=10f60 src_addr=924f8 src_addr_aligned=90000␛[0m
D (622) bootloader_flash: mmu set block paddr=0x000a0000 (was 0xffffffff)␛[0m
␛[0;32mI (622) esp_image: segment 6: paddr=0x000a3460 vaddr=0x400c0000 size=0x00064 (   100) load␛[0m
D (627) esp_image: free data page_count 0x00000032␛[0m
D (631) bootloader_flash: mmu set paddr=000a0000 count=1 size=64 src_addr=a3460 src_addr_aligned=a0000␛[0m
D (641) bootloader_flash: mmu set block paddr=0x000a0000 (was 0xffffffff)␛[0m
D (648) boot: Calculated hash: 4ab2b40b566c00aecc8602129c36d0f7a4d3e73fe7bb9d7c12007850bb44bf12␛[0m
D (656) bootloader_flash: mmu set paddr=000a0000 count=1 size=20 src_addr=a34d0 src_addr_aligned=a0000␛[0m
D (666) bootloader_flash: mmu set paddr=000a0000 count=1 size=20 src_addr=a34d0 src_addr_aligned=a0000␛[0m 
␛[0;32mI (687) boot: Loaded app from partition at offset 0x10000␛[0m
␛[0;32mI (704) boot: Set actual ota_seq=1 in otadata[0]␛[0m
␛[0;32mI (704) boot: Disabling RNG early entropy source...␛[0m
D (704) boot: Mapping segment 0 as DROM␛[0m
D (707) boot: Mapping segment 4 as IROM␛[0m
D (711) boot: calling set_cache_and_start_app␛[0m
D (716) boot: configure drom and irom and start␛[0m
D (720) boot: start: 0x40081388␛[0m
␛[0;32mI (724) cpu_start: Pro cpu up.␛[0m
␛[0;32mI (727) cpu_start: Application information:␛[0m
␛[0;32mI (732) cpu_start: Project name:     esp32-ble-test␛[0m
␛[0;32mI (738) cpu_start: App version:      aa0f802-dirty␛[0m
␛[0;32mI (743) cpu_start: Compile time:     Jun  2 2021 16:58:21␛[0m
␛[0;32mI (749) cpu_start: ELF file SHA256:  091797480364556a...␛[0m
␛[0;32mI (755) cpu_start: ESP-IDF:          3.40200.210118␛[0m
␛[0;32mI (761) cpu_start: Starting app cpu, entry point is 0x40081338␛[0m
␛[0;32mI (0) cpu_start: App cpu up.␛[0m
D (771) memory_layout: Checking 11 reserved memory ranges:␛[0m
D (776) memory_layout: Reserved memory range 0x3ffae000 - 0x3ffae6e0␛[0m
D (783) memory_layout: Reserved memory range 0x3ffae6e0 - 0x3ffaff10␛[0m
D (789) memory_layout: Reserved memory range 0x3ffb0000 - 0x3ffb6388␛[0m
D (796) memory_layout: Reserved memory range 0x3ffb8000 - 0x3ffb9a20␛[0m
D (802) memory_layout: Reserved memory range 0x3ffbdb28 - 0x3ffbdb5c␛[0m
D (809) memory_layout: Reserved memory range 0x3ffbdb60 - 0x3ffc3c60␛[0m
D (815) memory_layout: Reserved memory range 0x3ffe0000 - 0x3ffe0440␛[0m
D (821) memory_layout: Reserved memory range 0x3ffe3f20 - 0x3ffe4350␛[0m
D (828) memory_layout: Reserved memory range 0x40070000 - 0x40078000␛[0m
D (834) memory_layout: Reserved memory range 0x40078000 - 0x40080000␛[0m
D (841) memory_layout: Reserved memory range 0x40080000 - 0x4009611c␛[0m
D (847) memory_layout: Building list of available memory regions:␛[0m
D (853) memory_layout: Available memory region 0x3ffaff10 - 0x3ffb0000␛[0m
D (860) memory_layout: Available memory region 0x3ffb6388 - 0x3ffb8000␛[0m
D (866) memory_layout: Available memory region 0x3ffb9a20 - 0x3ffbdb28␛[0m
D (873) memory_layout: Available memory region 0x3ffc3c60 - 0x3ffc4000␛[0m
D (880) memory_layout: Available memory region 0x3ffc4000 - 0x3ffc6000␛[0m
D (886) memory_layout: Available memory region 0x3ffc6000 - 0x3ffc8000␛[0m
D (893) memory_layout: Available memory region 0x3ffc8000 - 0x3ffca000␛[0m
D (899) memory_layout: Available memory region 0x3ffca000 - 0x3ffcc000␛[0m
D (906) memory_layout: Available memory region 0x3ffcc000 - 0x3ffce000␛[0m
D (913) memory_layout: Available memory region 0x3ffce000 - 0x3ffd0000␛[0m
D (919) memory_layout: Available memory region 0x3ffd0000 - 0x3ffd2000␛[0m
D (926) memory_layout: Available memory region 0x3ffd2000 - 0x3ffd4000␛[0m
D (932) memory_layout: Available memory region 0x3ffd4000 - 0x3ffd6000␛[0m
D (939) memory_layout: Available memory region 0x3ffd6000 - 0x3ffd8000␛[0m
D (946) memory_layout: Available memory region 0x3ffd8000 - 0x3ffda000␛[0m
D (952) memory_layout: Available memory region 0x3ffda000 - 0x3ffdc000␛[0m
D (959) memory_layout: Available memory region 0x3ffdc000 - 0x3ffde000␛[0m
D (965) memory_layout: Available memory region 0x3ffde000 - 0x3ffe0000␛[0m
D (972) memory_layout: Available memory region 0x3ffe0440 - 0x3ffe3f20␛[0m
D (979) memory_layout: Available memory region 0x3ffe4350 - 0x3ffe8000␛[0m
D (985) memory_layout: Available memory region 0x3ffe8000 - 0x3fff0000␛[0m
D (992) memory_layout: Available memory region 0x3fff0000 - 0x3fff8000␛[0m
D (998) memory_layout: Available memory region 0x3fff8000 - 0x3fffc000␛[0m
D (1005) memory_layout: Available memory region 0x3fffc000 - 0x40000000␛[0m
D (1012) memory_layout: Available memory region 0x4009611c - 0x40098000␛[0m
D (1018) memory_layout: Available memory region 0x40098000 - 0x4009a000␛[0m
D (1025) memory_layout: Available memory region 0x4009a000 - 0x4009c000␛[0m
D (1032) memory_layout: Available memory region 0x4009c000 - 0x4009e000␛[0m
D (1038) memory_layout: Available memory region 0x4009e000 - 0x400a0000␛[0m
␛[0;32mI (1045) heap_init: Initializing. RAM available for dynamic allocation:␛[0m
D (1052) heap_init: New heap initialised at 0x3ffaff10␛[0m
␛[0;32mI (1058) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM␛[0m
D (1064) heap_init: New heap initialised at 0x3ffb6388␛[0m
␛[0;32mI (1069) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM␛[0m
D (1075) heap_init: New heap initialised at 0x3ffb9a20␛[0m
␛[0;32mI (1080) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM␛[0m
D (1087) heap_init: New heap initialised at 0x3ffc3c60␛[0m
␛[0;32mI (1092) heap_init: At 3FFC3C60 len 0001C3A0 (112 KiB): DRAM␛[0m
␛[0;32mI (1098) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM␛[0m
␛[0;32mI (1105) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM␛[0m
D (1111) heap_init: New heap initialised at 0x4009611c␛[0m
␛[0;32mI (1116) heap_init: At 4009611C len 00009EE4 (39 KiB): IRAM␛[0m
␛[0;32mI (1123) cpu_start: Pro cpu start user code␛[0m
D (1135) clk: RTC_SLOW_CLK calibration value: 3685158␛[0m
D (1144) intr_alloc: Connected src 46 to int 2 (cpu 0)␛[0m
D (1145) intr_alloc: Connected src 17 to int 3 (cpu 0)␛[0m
D (1145) intr_alloc: Connected src 24 to int 9 (cpu 0)␛[0m
D (1150) FLASH_HAL: extra_dummy: 1␛[0m
D (1154) spi_flash: trying chip: issi␛[0m
D (1158) spi_flash: trying chip: gd␛[0m
␛[0;32mI (1161) spi_flash: detected chip: gd␛[0m
␛[0;32mI (1166) spi_flash: flash io: dio␛[0m
␛[0;32mI (1170) cpu_start: Starting scheduler on PRO CPU.␛[0m
D (0) intr_alloc: Connected src 25 to int 2 (cpu 1)␛[0m
␛[0;32mI (0) cpu_start: Starting scheduler on APP CPU.␛[0m
D (1185) heap_init: New heap initialised at 0x3ffe0440␛[0m
D (1195) heap_init: New heap initialised at 0x3ffe4350␛[0m
D (1205) intr_alloc: Connected src 16 to int 12 (cpu 0)␛[0m
Starting main
Not ULP wakeup, initializing main prog
Starting NimBLE Server
D (2715) partition: Loading the partition table␛[0m
D (2725) BTDM_INIT: Release DRAM [0x3ffb2730] - [0x3ffb6388]␛[0m
␛[0;32mI (2725) BTDM_INIT: BT controller compile version [a4c513b]␛[0m
D (2725) BTDM_INIT: .data initialise [0x3ffae6e0] <== [0x4000d890]␛[0m
D (2725) BTDM_INIT: .bss initialise [0x3ffb0000] - [0x3ffb09a8]␛[0m
D (2735) BTDM_INIT: .bss initialise [0x3ffb09a8] - [0x3ffb1ddc]␛[0m
D (2745) BTDM_INIT: .bss initialise [0x3ffb1ddc] - [0x3ffb2730]␛[0m
D (2745) BTDM_INIT: .bss initialise [0x3ffb8000] - [0x3ffb9a20]␛[0m
D (2755) BTDM_INIT: .bss initialise [0x3ffbdb28] - [0x3ffbdb5c]␛[0m
␛[0;32mI (2755) system_api: Base MAC address is not set␛[0m
␛[0;32mI (2765) system_api: read default base MAC address from EFUSE␛[0m
D (2775) efuse: coding scheme 0␛[0m
D (2775) efuse: In EFUSE_BLK0__DATA2_REG is used 8 bits starting with 8 bit␛[0m
D (2785) efuse: coding scheme 0␛[0m
D (2785) efuse: In EFUSE_BLK0__DATA2_REG is used 8 bits starting with 0 bit␛[0m
D (2795) efuse: coding scheme 0␛[0m
D (2795) efuse: In EFUSE_BLK0__DATA1_REG is used 8 bits starting with 24 bit␛[0m
D (2805) efuse: coding scheme 0␛[0m
D (2805) efuse: In EFUSE_BLK0__DATA1_REG is used 8 bits starting with 16 bit␛[0m
D (2815) efuse: coding scheme 0␛[0m
D (2815) efuse: In EFUSE_BLK0__DATA1_REG is used 8 bits starting with 8 bit␛[0m
D (2825) efuse: coding scheme 0␛[0m
D (2825) efuse: In EFUSE_BLK0__DATA1_REG is used 8 bits starting with 0 bit␛[0m
D (2835) efuse: coding scheme 0␛[0m
D (2835) efuse: In EFUSE_BLK0__DATA2_REG is used 8 bits starting with 16 bit␛[0m
␛[0;32mI (2845) phy_init: phy_version 4660,0162888,Dec 23 2020␛[0m
D (2845) phy_init: loading PHY init data from application binary␛[0m
D (2855) nvs: nvs_open_from_partition phy 0␛[0m
D (2855) nvs: nvs_get cal_version 4␛[0m
D (2865) nvs: nvs_get_str_or_blob cal_mac␛[0m
D (2865) efuse: coding scheme 0␛[0m
D (2875) efuse: In EFUSE_BLK0__DATA2_REG is used 8 bits starting with 8 bit␛[0m
D (2875) efuse: coding scheme 0␛[0m
D (2885) efuse: In EFUSE_BLK0__DATA2_REG is used 8 bits starting with 0 bit␛[0m
D (2885) efuse: coding scheme 0␛[0m
D (2895) efuse: In EFUSE_BLK0__DATA1_REG is used 8 bits starting with 24 bit␛[0m
D (2895) efuse: coding scheme 0␛[0m
D (2905) efuse: In EFUSE_BLK0__DATA1_REG is used 8 bits starting with 16 bit␛[0m
D (2905) efuse: coding scheme 0␛[0m
D (2915) efuse: In EFUSE_BLK0__DATA1_REG is used 8 bits starting with 8 bit␛[0m
D (2915) efuse: coding scheme 0␛[0m
D (2925) efuse: In EFUSE_BLK0__DATA1_REG is used 8 bits starting with 0 bit␛[0m
D (2925) efuse: coding scheme 0␛[0m
D (2935) efuse: In EFUSE_BLK0__DATA2_REG is used 8 bits starting with 16 bit␛[0m
D (2935) nvs: nvs_get_str_or_blob cal_data␛[0m
D (2955) nvs: nvs_close 1␛[0m
D (2955) efuse: coding scheme 0␛[0m
D (2955) efuse: In EFUSE_BLK0__DATA2_REG is used 8 bits starting with 8 bit␛[0m
D (2955) efuse: coding scheme 0␛[0m
D (2955) efuse: In EFUSE_BLK0__DATA2_REG is used 8 bits starting with 0 bit␛[0m
D (2965) efuse: coding scheme 0␛[0m
D (2965) efuse: In EFUSE_BLK0__DATA1_REG is used 8 bits starting with 24 bit␛[0m
D (2975) efuse: coding scheme 0␛[0m
D (2975) efuse: In EFUSE_BLK0__DATA1_REG is used 8 bits starting with 16 bit␛[0m
D (2985) efuse: coding scheme 0␛[0m
D (2995) efuse: In EFUSE_BLK0__DATA1_REG is used 8 bits starting with 8 bit␛[0m
D (2995) efuse: coding scheme 0␛[0m
D (3005) efuse: In EFUSE_BLK0__DATA1_REG is used 8 bits starting with 0 bit␛[0m
D (3005) efuse: coding scheme 0␛[0m
D (3015) efuse: In EFUSE_BLK0__DATA2_REG is used 8 bits starting with 16 bit␛[0m
D (3355) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3355) nvs: nvs_get_str_or_blob our_sec_1␛[0m
D (3355) nvs: nvs_close 2␛[0m
D (3355) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3365) nvs: nvs_get_str_or_blob our_sec_2␛[0m
D (3365) nvs: nvs_close 3␛[0m
D (3365) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3375) nvs: nvs_get_str_or_blob our_sec_3␛[0m
D (3375) nvs: nvs_close 4␛[0m
D (3385) NIMBLE_NVS: ble_store_config_our_secs restored 0 bonds␛[0m
D (3385) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3395) nvs: nvs_get_str_or_blob peer_sec_1␛[0m
D (3395) nvs: nvs_close 5␛[0m
D (3395) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3405) nvs: nvs_get_str_or_blob peer_sec_2␛[0m
D (3405) nvs: nvs_close 6␛[0m
D (3415) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3415) nvs: nvs_get_str_or_blob peer_sec_3␛[0m
D (3425) nvs: nvs_close 7␛[0m
D (3425) NIMBLE_NVS: ble_store_config_peer_secs restored 0 bonds␛[0m
D (3425) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3435) nvs: nvs_get_str_or_blob cccd_sec_1␛[0m
D (3435) nvs: nvs_close 8␛[0m
D (3445) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3445) nvs: nvs_get_str_or_blob cccd_sec_2␛[0m
D (3455) nvs: nvs_close 9␛[0m
D (3455) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3455) nvs: nvs_get_str_or_blob cccd_sec_3␛[0m
D (3465) nvs: nvs_close 10␛[0m
D (3465) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3475) nvs: nvs_get_str_or_blob cccd_sec_4␛[0m
D (3475) nvs: nvs_close 11␛[0m
D (3475) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3485) nvs: nvs_get_str_or_blob cccd_sec_5␛[0m
D (3485) nvs: nvs_close 12␛[0m
D (3485) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3495) nvs: nvs_get_str_or_blob cccd_sec_6␛[0m
D (3495) nvs: nvs_close 13␛[0m
D (3505) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3505) nvs: nvs_get_str_or_blob cccd_sec_7␛[0m
D (3515) nvs: nvs_close 14␛[0m
D (3515) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3515) nvs: nvs_get_str_or_blob cccd_sec_8␛[0m
D (3525) nvs: nvs_close 15␛[0m
D (3525) NIMBLE_NVS: ble_store_config_cccds restored 0 bonds␛[0m
D (3535) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3535) nvs: nvs_get_str_or_blob p_dev_rec_1␛[0m
D (3545) nvs: nvs_close 16␛[0m
D (3545) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3545) nvs: nvs_get_str_or_blob p_dev_rec_2␛[0m
D (3555) nvs: nvs_close 17␛[0m
D (3555) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3565) nvs: nvs_get_str_or_blob p_dev_rec_3␛[0m
D (3565) nvs: nvs_close 18␛[0m
D (3565) nvs: nvs_open_from_partition nimble_bond 1␛[0m
D (3575) nvs: nvs_get_str_or_blob p_dev_rec_4␛[0m
D (3575) nvs: nvs_close 19␛[0m
D (3585) NIMBLE_NVS: peer_dev_rec restored 0 records␛[0m
␛[0;32mI (3585) NimBLEDevice: BLE Host Task Started␛[0m
ble_hs_hci_cmd_send: ogf=0x03 ocf=0x0003 len=0
0x03 0x0c 0x00
Command complete: cmd_pkts=5 ogf=0x3 ocf=0x3 status=0 
ble_hs_hci_cmd_send: ogf=0x04 ocf=0x0001 len=0
0x01 0x10 0x00
Command complete: cmd_pkts=5 ogf=0x4 ocf=0x1 status=0 hci_ver=8 hci_rev=782 lmp_ver=8 mfrg=96 lmp_subver=782
ble_hs_hci_cmd_send: ogf=0x04 ocf=0x0003 len=0
0x03 0x10 0x00
Command complete: cmd_pkts=5 ogf=0x4 ocf=0x3 status=0 supp_feat=0x877bffdbfecdeebf
ble_hs_hci_cmd_send: ogf=0x03 ocf=0x0001 len=8
0x01 0x0c 0x08 0x90 0x80 0x00 0x02 0x00 0x80 0x00 0x20
Command complete: cmd_pkts=5 ogf=0x3 ocf=0x1 status=0
ble_hs_hci_cmd_send: ogf=0x03 ocf=0x0063 len=8
0x63 0x0c 0x08 0x00 0x00 0x80 0x00 0x00 0x00 0x00 0x00
Command complete: cmd_pkts=5 ogf=0x3 ocf=0x63 status=0
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0001 len=8
0x01 0x20 0x08 0x7f 0x06 0x00 0x00 0x00 0x00 0x00 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x1 status=0
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0002 len=0
0x02 0x20 0x00
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x2 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0003 len=0
0x03 0x20 0x00
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x3 status=0
ble_hs_hci_cmd_send: ogf=0x04 ocf=0x0009 len=0
0x09 0x10 0x00
Command complete: cmd_pkts=5 ogf=0x4 ocf=0x9 status=0 bd_addr=10:52:1c:88:6c:ba
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0018 len=0
0x18 0x20 0x00
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x18 status=0 rand=0x99fc62d8cf753e02
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0018 len=0
0x18 0x20 0x00
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x18 status=0 rand=0xcb9d3ac4ad018909
Device added to RL, Resolving list count = 1
ble_hs_hci_cmd_send: ogf=0x03 ocf=0x0031 len=1
0x31 0x0c 0x01 0x01 
Command complete: cmd_pkts=5 ogf=0x3 ocf=0x31 status=0
ble_hs_hci_cmd_send: ogf=0x03 ocf=0x0033 len=7
0x33 0x0c 0x07 0xff 0x00 0x00 0x0c 0x00 0x00 0x00
Command complete: cmd_pkts=5 ogf=0x3 ocf=0x33 status=0 
looking up peer sec;
␛[0;32mI (3765) NimBLEDevice: NimBle host synced.␛[0m
D (3765) NimBLEDevice: Setting bonding: 0, mitm: 0, sc: 1␛[0m
D (3775) NimBLEServer: >> createService - 0xdead␛[0m
D (3775) NimBLEServer: << createService␛[0m
D (3775) NimBLECharacteristic: >> setValue: length=7, data=42757267657200, characteristic UUID=0xbeef␛[0m
D (3785) NimBLECharacteristic: << setValue␛[0m
D (3795) NimBLEUUID: Comparing UUIDs; type 16 to 16; UUID 0x2904 to 0x2902␛[0m
D (3795) NimBLEUUID: Comparing UUIDs; type 16 to 16; UUID 0x2904 to 0x2904␛[0m
D (3805) NimBLEServer: >> createService - 0xbaad␛[0m
D (3815) NimBLEUUID: Comparing UUIDs; type 16 to 16; UUID 0xdead to 0xbaad␛[0m
D (3815) NimBLEServer: << createService␛[0m
D (3825) NimBLECharacteristic: >> setValue: length=6, data=467269657300, characteristic UUID=0xf00d␛[0m    
D (3835) NimBLECharacteristic: << setValue␛[0m
D (3835) NimBLEUUID: Comparing UUIDs; type 16 to 16; UUID 0xc01d to 0x2902␛[0m
D (3845) NimBLEUUID: Comparing UUIDs; type 16 to 16; UUID 0xc01d to 0x2904␛[0m
D (3845) NimBLEService: >> start(): Starting service: UUID: 0xdead, handle: 0xffff␛[0m
D (3855) NimBLEService: Adding 1 characteristics for service UUID: 0xdead, handle: 0xffff␛[0m
D (3865) NimBLEService: << start()␛[0m
D (3865) NimBLEService: >> start(): Starting service: UUID: 0xbaad, handle: 0xffff␛[0m
D (3875) NimBLEService: Adding 1 characteristics for service UUID: 0xbaad, handle: 0xffff␛[0m
D (3885) NimBLEService: << start()␛[0m
D (3885) NimBLEAdvertising: >> Advertising start: customAdvData: 0, customScanResponseData: 0␛[0m
primary service
           uuid 0x1800
         handle 1
     end_handle 5
characteristic
           uuid 0x2a00
     def_handle 2
     val_handle 3
   min_key_size 0
          flags [READ]
characteristic
           uuid 0x2a01
     def_handle 4
     val_handle 5
   min_key_size 0
          flags [READ]
primary service
           uuid 0x1801
         handle 6
     end_handle 9
characteristic
           uuid 0x2a05
     def_handle 7
     val_handle 8
   min_key_size 0
          flags [INDICATE]
ccc descriptor
           uuid 0x2902
         handle 9
   min_key_size 0
          flags [READ|WRITE]
primary service
           uuid 0xdead
         handle 10
     end_handle 13
characteristic
           uuid 0xbeef
     def_handle 11
     val_handle 12
   min_key_size 0
          flags [READ|WRITE|READ_ENC|WRITE_ENC]
descriptor
           uuid 0x2904
         handle 13
   min_key_size 0
          flags [READ]
primary service
           uuid 0xbaad
         handle 14
     end_handle 18
characteristic
           uuid 0xf00d
     def_handle 15
     val_handle 16
   min_key_size 0
          flags [READ|WRITE|NOTIFY]
ccc descriptor
           uuid 0x2902
         handle 17
   min_key_size 0
          flags [READ|WRITE]
descriptor
           uuid 0xc01d
         handle 18
   min_key_size 0
          flags [READ|WRITE|WRITE_ENC]
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0009 len=32
0x09 0x20 0x20 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x9 status=0
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0008 len=32
0x08 0x20 0x20 0x11 0x02 0x01 0x06 0x05 0x03 0xad 0xde 0xad 0xba 0x07 0x09 0x4e 0x69 0x6d 0x42 0x4c 0x45 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x8 status=0 
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0006 len=15
0x06 0x20 0x0f 0x30 0x00 0x60 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x07 0x00
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x6 status=0
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x000a len=1
0x0a 0x20 0x01 0x01
Command complete: cmd_pkts=5 ogf=0x8 ocf=0xa status=0
D (4105) NimBLEAdvertising: << Advertising start␛[0m
Advertising Started
␛[0;32mI (4115) gpio: GPIO[13]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m 
␛[0;32mI (4125) gpio: GPIO[14]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
␛[0;32mI (4135) gpio: GPIO[19]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m 
␛[0;32mI (4145) gpio: GPIO[21]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
Button thread created...
Before main loop...
LE connection complete. handle=0 role=1 paddrtype=1 addr=4e.a6.7d.31.7c.ff local_rpa=0.0.0.0.0.0 peer_rpa=0.0.0.0.0.0 itvl=36 latency=0 spvn_tmo=500 mca=0
0xff 0x7c 0x31 0x7d 0xa6 0x4e
D (9945) NimBLEServer: >> handleGapEvent: BLE_GAP_EVENT_CONNECT ␛[0m
Client connected
D (9955) NimBLEAdvertising: >> Advertising start: customAdvData: 0, customScanResponseData: 0␛[0m
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0006 len=15
0x06 0x20 0x0f 0x30 0x00 0x60 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x07 0x00
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x6 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x000a len=1
0x0a 0x20 0x01 0x01
Command complete: cmd_pkts=5 ogf=0x8 ocf=0xa status=0
D (10005) NimBLEAdvertising: << Advertising start␛[0m
Client address: 4e:a6:7d:31:7c:ff
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0016 len=2
0x16 0x20 0x02 0x00 0x00
Command Status: status=0 cmd_pkts=5 ocf=0x16 ogf=0x8
LE Remote Used Features. handle=0 feat=ff 00 00 00 00 00 00 00
D (10115) NimBLEUUID: Comparing UUIDs; type 16 to 16; UUID 0xdead to 0xbaad␛[0m
D (10115) NimBLEUUID: Comparing UUIDs; type 16 to 16; UUID 0xbaad to 0xbaad␛[0m
D (10115) NimBLEUUID: Comparing UUIDs; type 16 to 16; UUID 0xf00d to 0xf00d␛[0m
D (10125) NimBLECharacteristic: >> notify: length: 6␛[0m
D (10125) NimBLECharacteristic: << notify: No clients subscribed.␛[0m
LE Remote Connection Parameter Request. handle=0 min_itvl=6 max_itvl=6 latency=0 timeout=500
D (10275) NimBLEServer: >> handleGapEvent: BLE_GAP_EVENT_CONN_UPDATE_REQ␛[0m
D (10275) NimBLEServer: << handleGATTServerEvent␛[0m
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0020 len=14
0x20 0x20 0x0e 0x00 0x00 0x06 0x00 0x06 0x00 0x00 0x00 0xf4 0x01 0x00 0x00 0x00 0x00
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x20 status=0
ble_hs_hci_evt_acl_process(): conn_handle=0 pb=2 len=11 data=0x07 0x00 0x04 0x00 0x10 0x01 0x00 0xff 0xff 0x00 0x28
rxed att command: read group type req; conn=0 start_handle=0x0001 end_handle=0xffff
txed att command: read group type rsp; conn=0 length=6
host tx hci data; handle=0 length=24
ble_hs_hci_acl_tx(): 0x00 0x00 0x18 0x00 0x14 0x00 0x04 0x00 0x11 0x06 0x01 0x00 0x05 0x00 0x00 0x18 0x06 0x00 0x09 0x00 0x01 0x18 0x0a 0x00 0x0d 0x00 0xad 0xde
Number of Completed Packets: num_handles=1
handle:0 pkts:1
ble_hs_hci_evt_acl_process(): conn_handle=0 pb=2 len=11 data=0x07 0x00 0x04 0x00 0x10 0x0e 0x00 0xff 0xff 0x00 0x28
rxed att command: read group type req; conn=0 start_handle=0x000e end_handle=0xffff
txed att command: read group type rsp; conn=0 length=6
host tx hci data; handle=0 length=12
ble_hs_hci_acl_tx(): 0x00 0x00 0x0c 0x00 0x08 0x00 0x04 0x00 0x11 0x06 0x0e 0x00 0xff 0xff 0xad 0xba       
Number of Completed Packets: num_handles=1
handle:0 pkts:1
ble_hs_hci_evt_acl_process(): conn_handle=0 pb=2 len=11 data=0x07 0x00 0x04 0x00 0x08 0x01 0x00 0x05 0x00 0x02 0x28
rxed att command: read type req; conn=0 start_handle=0x0001 end_handle=0x0005
txed att command: error rsp; conn=0 req_op=8 handle=0x0001 error_code=10
host tx hci data; handle=0 length=9
ble_hs_hci_acl_tx(): 0x00 0x00 0x09 0x00 0x05 0x00 0x04 0x00 0x01 0x08 0x01 0x00 0x0a 
Number of Completed Packets: num_handles=1
handle:0 pkts:1
ble_hs_hci_evt_acl_process(): conn_handle=0 pb=2 len=11 data=0x07 0x00 0x04 0x00 0x08 0x01 0x00 0x05 0x00 0x03 0x28
rxed att command: read type req; conn=0 start_handle=0x0001 end_handle=0x0005
txed att command: read type rsp; conn=0 length=7
host tx hci data; handle=0 length=20
ble_hs_hci_acl_tx(): 0x00 0x00 0x14 0x00 0x10 0x00 0x04 0x00 0x09 0x07 0x02 0x00 0x02 0x03 0x00 0x00 0x2a 0x04 0x00 0x02 0x05 0x00 0x01 0x2a
Number of Completed Packets: num_handles=1
handle:0 pkts:1
LE Connection Update Complete. handle=0 itvl=6 latency=0 timeout=500
D (10725) NimBLEServer: >> handleGapEvent: BLE_GAP_EVENT_CONN_UPDATE␛[0m
D (10725) NimBLEServer: Connection parameters updated.␛[0m
ble_hs_hci_evt_acl_process(): conn_handle=0 pb=2 len=11 data=0x07 0x00 0x04 0x00 0x08 0x05 0x00 0x05 0x00 0x03 0x28
rxed att command: read type req; conn=0 start_handle=0x0005 end_handle=0x0005
txed att command: error rsp; conn=0 req_op=8 handle=0x0005 error_code=10
host tx hci data; handle=0 length=9
ble_hs_hci_acl_tx(): 0x00 0x00 0x09 0x00 0x05 0x00 0x04 0x00 0x01 0x08 0x05 0x00 0x0a 
Number of Completed Packets: num_handles=1
handle:0 pkts:1
ble_hs_hci_evt_acl_process(): conn_handle=0 pb=2 len=11 data=0x07 0x00 0x04 0x00 0x08 0x06 0x00 0x09 0x00 0x02 0x28
rxed att command: read type req; conn=0 start_handle=0x0006 end_handle=0x0009
txed att command: error rsp; conn=0 req_op=8 handle=0x0006 error_code=10
host tx hci data; handle=0 length=9
ble_hs_hci_acl_tx(): 0x00 0x00 0x09 0x00 0x05 0x00 0x04 0x00 0x01 0x08 0x06 0x00 0x0a
Number of Completed Packets: num_handles=1
handle:0 pkts:1
ble_hs_hci_evt_acl_process(): conn_handle=0 pb=2 len=11 data=0x07 0x00 0x04 0x00 0x08 0x06 0x00 0x09 0x00 0x03 0x28
rxed att command: read type req; conn=0 start_handle=0x0006 end_handle=0x0009
txed att command: read type rsp; conn=0 length=7
host tx hci data; handle=0 length=13
ble_hs_hci_acl_tx(): 0x00 0x00 0x0d 0x00 0x09 0x00 0x04 0x00 0x09 0x07 0x07 0x00 0x20 0x08 0x00 0x05 0x2a  
Number of Completed Packets: num_handles=1
handle:0 pkts:1
ble_hs_hci_evt_acl_process(): conn_handle=0 pb=2 len=11 data=0x07 0x00 0x04 0x00 0x08 0x08 0x00 0x09 0x00 0x03 0x28
rxed att command: read type req; conn=0 start_handle=0x0008 end_handle=0x0009
txed att command: error rsp; conn=0 req_op=8 handle=0x0008 error_code=10
host tx hci data; handle=0 length=9
ble_hs_hci_acl_tx(): 0x00 0x00 0x09 0x00 0x05 0x00 0x04 0x00 0x01 0x08 0x08 0x00 0x0a 
Number of Completed Packets: num_handles=1
handle:0 pkts:1
ble_hs_hci_evt_acl_process(): conn_handle=0 pb=2 len=9 data=0x05 0x00 0x04 0x00 0x04 0x09 0x00 0x09 0x00 
rxed att command: find info req; conn=0 start_handle=0x0009 end_handle=0x0009
txed att command: find info rsp; conn=0 format=1
host tx hci data; handle=0 length=10
ble_hs_hci_acl_tx(): 0x00 0x00 0x0a 0x00 0x06 0x00 0x04 0x00 0x05 0x01 0x09 0x00 0x02 0x29
Number of Completed Packets: num_handles=1
handle:0 pkts:1
ble_hs_hci_evt_acl_process(): conn_handle=0 pb=2 len=11 data=0x07 0x00 0x04 0x00 0x08 0x0a 0x00 0x0d 0x00 0x02 0x28
rxed att command: read type req; conn=0 start_handle=0x000a end_handle=0x000d
txed att command: error rsp; conn=0 req_op=8 handle=0x000a error_code=10
host tx hci data; handle=0 length=9
ble_hs_hci_acl_tx(): 0x00 0x00 0x09 0x00 0x05 0x00 0x04 0x00 0x01 0x08 0x0a 0x00 0x0a
Number of Completed Packets: num_handles=1
handle:0 pkts:1
ble_hs_hci_evt_acl_process(): conn_handle=0 pb=2 len=11 data=0x07 0x00 0x04 0x00 0x08 0x0a 0x00 0x0d 0x00 0x03 0x28
rxed att command: read type req; conn=0 start_handle=0x000a end_handle=0x000d
txed att command: read type rsp; conn=0 length=7
host tx hci data; handle=0 length=13
ble_hs_hci_acl_tx(): 0x00 0x00 0x0d 0x00 0x09 0x00 0x04 0x00 0x09 0x07 0x0b 0x00 0x0a 0x0c 0x00 0xef 0xbe 
Number of Completed Packets: num_handles=1
handle:0 pkts:1
ble_hs_hci_evt_acl_process(): conn_handle=0 pb=2 len=11 data=0x07 0x00 0x04 0x00 0x08 0x0c 0x00 0x0d 0x00 0x03 0x28
rxed att command: read type req; conn=0 start_handle=0x000c end_handle=0x000d
txed att command: error rsp; conn=0 req_op=8 handle=0x000c error_code=10
host tx hci data; handle=0 length=9
ble_hs_hci_acl_tx(): 0x00 0x00 0x09 0x00 0x05 0x00 0x04 0x00 0x01 0x08 0x0c 0x00 0x0a
Number of Completed Packets: num_handles=1
handle:0 pkts:1
D (12135) NimBLEUUID: Comparing UUIDs; type 16 to 16; UUID 0xdead to 0xbaad␛[0m
D (12135) NimBLEUUID: Comparing UUIDs; type 16 to 16; UUID 0xbaad to 0xbaad␛[0m
D (12135) NimBLEUUID: Comparing UUIDs; type 16 to 16; UUID 0xf00d to 0xf00d␛[0m
D (12145) NimBLECharacteristic: >> notify: length: 6␛[0m
D (12145) NimBLECharacteristic: << notify: No clients subscribed.␛[0m
D (14155) NimBLEUUID: Comparing UUIDs; type 16 to 16; UUID 0xdead to 0xbaad␛[0m
D (14155) NimBLEUUID: Comparing UUIDs; type 16 to 16; UUID 0xbaad to 0xbaad␛[0m
D (14155) NimBLEUUID: Comparing UUIDs; type 16 to 16; UUID 0xf00d to 0xf00d␛[0m
D (14165) NimBLECharacteristic: >> notify: length: 6␛[0m
D (14165) NimBLECharacteristic: << notify: No clients subscribed.␛[0m
Disconnection Complete: status=0 handle=0 reason=8
D (16155) NimBLEServer: >> handleGapEvent: BLE_GAP_EVENT_DISCONNECT␛[0m
Client disconnected - start advertising
D (16155) NimBLEAdvertising: >> Advertising start: customAdvData: 0, customScanResponseData: 0␛[0m
␛[0;33mW (16165) NimBLEAdvertising: Advertising already active␛[0m
D (16165) NimBLEServerCallbacks: onDisconnect(): Default␛[0m
D (16175) NimBLEAdvertising: >> Advertising start: customAdvData: 0, customScanResponseData: 0␛[0m
␛[0;33mW (16185) NimBLEAdvertising: Advertising already active␛[0m
```

</details>

**Comment by h2zero** [comment]
That's very odd, the esp32 is also logging the disconnect as a timeout but I don't see anything to suggest why. Are you connected to it with a custom app? If so could you try with nRFconnect and check if you have the same error?

**Comment by AlexHartford** [comment]
We have been using nRFConnect... We're pretty stumped :(

**Comment by h2zero** [comment]
Ok, I will see if I can reproduce the issue here and hopefully find the cause. Which version/commit of IDF are you on?

**Comment by AlexHartford** [comment]
We're on the latest platformio version (3.2.1) which I believe only uses esp-idf version 4.2.1.

**Comment by h2zero** [comment]
Thanks, I don't use platformio so I'll have to look at the commit it's using and see what I can come up with.

**Comment by AlexHartford** [comment]
https://github.com/AlexHartford/esp32-ble-test/blob/master/sdkconfig

**Comment by h2zero** [comment]
Thanks, I should have noticed that there, focused on the code :smiley:

**Comment by AlexHartford** [comment]
No worries! We have still been unable to track the issue down in the meantime :disappointed:

**Comment by h2zero** [comment]
I haven't had time to test this yet, sorry. I should be able to tonight or tomorrow.

**Comment by h2zero** [comment]
@AlexHartford I am unable to reproduce the issue. I used your repo and it connects/reconnects with no error.
I'll test this more later on with different client devices and see what happens.

**Comment by AlexHartford** [comment]
Thanks for your help, when running it directly through idf it works, it appears platform.io was causing the issue somehow. We wouldn't have thought to try it if you had not been able to get it working, and you mentioned you don't use platform.io. Cheers!

**Comment by h2zero** [comment]
Actually I tested it in PlatformIO and IDF and it worked the same in both. Maybe something is different in your setup but I don't know PlatformIO well enough to suggest anything.

Glad you have it working!
